name: make_drake

on:
    push:
        branches: master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup R
              uses: r-lib/actions/setup-r@master

            - name: Create report file
              run: date +%s > report.txt

            - name: Commit report
              run: |
                  git config --global user.name 'Adam Altmejd'
                  git config --global user.email 'adamaltmejd@users.noreply.github.com'
                  git add --all
                  git commit -m "Test"
                  git push
